config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  
  resources :curriculums, except: [:index]
  get 'about_me', to: 'curriculums#index', as: 'about'
  get 'presentation', to: 'curriculums#presentation', as: 'presentation'
  get 'education', to: 'curriculums#education', as: 'education'
  get 'experience', to: 'curriculums#experience', as: 'experience'
  get 'other', to: 'curriculums#other', as: 'other'

  resources :portfolios do
    put :sort, on: :collection
  
     # get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  end
  # get 'portfolio', to: 'portfolios#index', as: 'portfolios'
  # get 'portfolio', to: 'portfolios#index'

  

  root to: 'pages#home'
  # Changing behavour of about me => pages#about is now ADMIN PAGE 
  get 'nns-admin-page', to: 'pages#admin', as: 'admin'
  get 'credit',to: 'pages#credit', as: 'credit'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	validates_presence_of :title, :content#, :main_image, :button_image
	has_many :technology_tags
   accepts_nested_attributes_for :technology_tags, 
							     allow_destroy: true,
                                 reject_if: lambda { |attrs| attrs['name'].blank?}
 
	def self.by_position
		order("position ASC")
	end

  mount_uploader :button_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolios, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:new,:edit,:update,:destroy]
  layout 'portfolio'

	def index
		@portfolio_items=Portfolio.by_position
    @page_title = "Portfolio"
	end

  def sort
    params[:order].each do |k,v|
      Portfolio.find(v[:id]).update(position: v[:position])
    end

    # render nothing: true
    head :ok
    # render body: nil
  end

	# new only renders, not creates!
	def new
    @page_title = "New Potfolio "

		# comment out below line and in new.html.erb use for_with()
		@portfolio_item = Portfolio.new

    #hard code for giving 3 technologies to each new portfolio item
    # 3.times {@portfolio_item.technology_tags.build}
	end

	def create
		@portfolio_item = Portfolio.new(portfolio_item_params)

   	 respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Item to your portfolio was successfully created.' }
        # format.json { render :show, status: :created, location: @portfolio_item } WERE NOT USING JSON
      else
        format.html { render :new }
        # format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
     end
	end

	def edit
    @page_title = "Edit Portfolio "

	end

	 def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to portfolios_path, notice: 'Your item was successfully updated.' }
        # format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        # format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }  
      end
     end
  	end

  	def show
      @page_title = @portfolio_item.title
  	end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Your item was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
	
	# Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :content,
                                        :main_image,
                                        :button_image,
                                        technology_tags_attributes:  [:id, :name, :_destroy]                              
                                        )
    end

    def set_portfolios
    	@portfolio_item = Portfolio.find(params[:id])
    end


end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    #byebug
  
    if img.model.main_image? || img.model.button_image?         
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'full'
      image_generator(height: '600', width: '400')
    
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row marketing">
    <div class="col-md-6">
      <div class=" form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class=" form-group">
        <%= form.label :subtitle %>
        <%= form.text_area :subtitle, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <br>
      <div class=" form-group">
        <label class="btn btn-green btn-padding text-white"> Upload a main image file
          <%= form.file_field :main_image, style: 'display:none' %>
        </label>
        <label class="btn btn-green btn-padding text-white"> Upload a button image file
        <%= form.file_field :button_image, style: 'display:none' %>
        </label>
        <br>
        <div class=" form-group tech-tag">
          <p> Tags for Portfolio item </p>
          <%= form.fields_for :technology_tags do |tech_form|%>
            <%= render 'technology_tag_fields', f: tech_form %>
          <% end %>
        </div>
        <div>
          <%= link_to_add_association 'Add Technology', form, :technology_tags %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
        <div class=" form-group">
          <%= form.label :content %>
          <%= form.text_area :content, class: "form-control", rows: 13%>
       </div>
    </div>
  </div>
  <div class="action">
    <%= form.submit "SUBMIT", class: "btn btn-green btn-padding text-white" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4"> 
  <div class="card" data-id="<%= portfolio_item.id %>">
    <p>
      <a href="<%= portfolio_path(portfolio_item) %>">
        <%= image_tag  portfolio_img(portfolio_item.button_image, 'thumb'), width: '100%', height: '200px'  %> 
      </a>
    </p>
    <p class="card-text">
    	<span><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></span>
    	<%= crud_helper("Edit",portfolio_item.title,edit_portfolio_path(portfolio_item),nil) %>
      <%= crud_helper("Delete",portfolio_item.title,nil,portfolio_item) %>
    </p>
  </div>
</div>

app/views/portfolios/_portfolio_jumbotron.html.erb
<% if current_page?(portfolios_path) %>
	<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">My projects</h1>
      <p class="lead text-muted " > 
        Here I'd like to share with you my favourite projects- some of them are simple and small, some of them are bigger. 
        In this portfolio I show all my work - in acoustics and any regular or web appss.
      </p>
      <p>
        <%= link_to "See about me", about_path, class: "btn btn-green text-white"%> 
        <%= link_to "Contact", contact_path, class: "btn btn-green-secondary text-white" %>
      </p>
      <p>
        <%= crud_helper("New","Portfolio",new_portfolio_path,nil) %>
      </p>
    </div>
	</section>
<% end %>

app/views/portfolios/_technology_tag_fields.html.erb
<div class="form-group nested-fields">
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div> 

app/views/portfolios/edit.html.erb
<div class="site-wrapper">
	<div class="site-wrapper-inner">
 		<div class="cover-container">
			 <div class="jumbotron container portfolio-container">
			 	<h1 class="jumbotron-heading"> Edit: </h1>
				<%= render 'form', portfolio_item: @portfolio_item %>
			 </div>
		</div>
	</div>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
      <div class="row <%= sortable_helper %> ">
  			<%= render partial: 'portfolio_item', collection: @portfolio_items %>		
		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<section class="jumbotron text-center jumber">
    <div class="container  portfolio-contain">      	
      <h1 class="jumbotron-heading">New Portfolio item</h1>
      <br>
      <%= render 'form', portfolio_item: @portfolio_item %>
    </div>
</section>

app/views/portfolios/show.html.erb
<div class="container text-center portfolio-container"> 
 	<div class="row marketing" >
 		<div class="col-md-4 ">  	
		  <h4><strong><%= @portfolio_item.title %> </strong></h4>
			<br>
			<p class="text-left" style="padding-left: 2%;">
				<%= @portfolio_item.subtitle %>
			</p>
     	<br>
			<p class="text-left" style="padding-left: 2%;">
				<i>Technologies used: </i>
			</p>
			<% @portfolio_item.technology_tags.each do |t| %>
        <p class="text-left" style="padding-left: 3.5%;"> <%= t.name %></p>
      <% end %>
			<hr>	
		</div>
		<div class="col-md-8  main-img">	
			<p><%= image_tag portfolio_img(@portfolio_item.main_image, 'full'), width: '95%' %></p>
		</div>
	</div>
	<div class="col-md-12"> 
		<p>
			<!-- <%= @portfolio_item.content %> -->
			<%= markdown @portfolio_item.content %>
		</p>
	</div>
	<div class="text-left">
		<%= link_to "View All", portfolios_path %> 	
	</div>
</div>