config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  
  resources :curriculums, except: [:index]
  get 'about_me', to: 'curriculums#index', as: 'about'
  get 'presentation', to: 'curriculums#presentation', as: 'presentation'
  get 'education', to: 'curriculums#education', as: 'education'
  get 'experience', to: 'curriculums#experience', as: 'experience'
  get 'other', to: 'curriculums#other', as: 'other'

  resources :portfolios do
    put :sort, on: :collection
  
     # get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  end
  # get 'portfolio', to: 'portfolios#index', as: 'portfolios'
  # get 'portfolio', to: 'portfolios#index'

  

  root to: 'pages#home'
  # Changing behavour of about me => pages#about is now ADMIN PAGE 
  get 'nns-admin-page', to: 'pages#admin', as: 'admin'
  get 'credit',to: 'pages#credit', as: 'credit'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<div class="jumbotron win-height">
	<h3 style="text-align: center;">MY ADMIN PAGE</h3>
	<br>
	<div class="space">
		<%= login_helper("btn btn-darker") %>
	</div>
	<br>
	<h5 style="text-align: center;"> What would you like to change? </h5> 
	<br>
	<div class ="space">
			<%= link_to "See all CV", about_path, class: "btn btn-darker  btn-space" %> 
			<%= link_to "PORTFOLIO", portfolios_path, class: "btn btn-darker  btn-space"  %>
	</div>

	<div class="space" >
	 	<% if current_user %>
			<%= link_to "New CV", new_curriculum_path, class: "btn btn-darker  btn-space" %> 
			<%= link_to "New Portfolio", new_portfolio_path, class: "btn btn-darker  btn-space"  %>
		<% end %>
	</div>
	<div class="space hr-p">
		<hr>
		<p> All other changes, such as edit and delete are nearby each item :) </p>
	</div>							
</div>

app/views/pages/contact.html.erb
<!-- jumbotron class for card! -->

<div class="contact win-height">		
  <section id = "img-contact">
  <div class= "container">
    <p> 
      <img src="/images/nejt.JPG" class="rounded-circle img-small"> 
    </p>
  </div>
  </section>

  <section id= "txt-contact">
    <h5>Contact me via email: </h5>
    <p>
      <a href="mailto:nataliaxskowronek@gmail.com?subject=PortfolioContact" "email me" class="btn" >EMAIL ME</a> 
    </p>
    <br>
  </section>
  
  <h5> You can find me: </h5>
  <section id="icons-contact">
    <ul class="list-inline">
      <li class="list-inline-item"> 
        <a href="https://www.linkedin.com/in/natalia-skowronek-njt/"> 
          <i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
        </a> 
      </li>
      <li class="list-inline-item"> 
        <a href="http://gitlab.com/nejcik"> 
          <i class="fa fa-git fa-2x" aria-hidden="true"></i> 
        </a>
      </li>
      <li class="list-inline-item"> 
        <a href="http://github.com/nejcik"> 
          <i class="fa fa-github fa-2x" aria-hidden="true"></i>
        </a> 
      </li>
    </ul>
  </section>
</div>

app/views/pages/credit.html.erb
<div class="container min-height" style="padding-top: 12%;">
	<h3>Credit:</h3>
	<p>
		<a class="normal" href="http://www.iconninja.com/"> ICON NINJA </a>
	</p>
	<p>
		<a class="normal" href="http://www.thecuriouslycreative.com">http://www.thecuriouslycreative.com/</a>
	</p>

	<p>
		Text correction: Ola Dębska
	</p>
	<div>Icons made by <a class="normal" href="https://www.flaticon.com/authors/eucalyp" title="Eucalyp">Eucalyp</a> from <a  class="normal" href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a class="normal" href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

	<p>
		Background image by: Cassey Fyfe
	</p>
	<p>
		Photographies from "about me" page: Alicja Warchał. Mateusz Wójcik.
	</p>

	<p>
		Animation from homepage: <a class="normal" href="http://www.thecuriouslycreative.com/">Yoann</a>
	</p>
</div>

app/views/pages/home.html.erb
<%= render "shared/nav_home" %>
  <div class="win-height">
    <div class="container row" style="padding-top:3%">
      <div class=" container  pullRightLeft text-home">
        <%= link_to "HOME", root_path, class: "link-home"%>
        <%= link_to "ABOUT", about_path, class: "link-home" %>
        <%= link_to "PORTFOLIO", portfolios_path, class: "link-home" %>
        <%= link_to "CONTACT", contact_path, class: "link-home" %>
      </div>
    </div>
    <br>
    <div class = "row"  style="padding-bottom:5%">
      <div class="col-md-6 text-left text-center-sm ns-div" >
      </div>
      <div class="col-md-4 text-left text-center-sm ns-div" >
        <div class="container row text-home" style="padding-top:3%; max-width: 20%">
          <h3>Natalia</h3>
          <h3>Skowronek</h3>
          <h1>portfolio</h1>
        </div>
      </div>
    </div
  </div>